CREATE TABLE DESCENT.ITEM (
    NAME VARCHAR(30) NOT NULL CONSTRAINT DESCENT.ITEM_PK PRIMARY KEY,
    MESSAGE_CODE VARCHAR(30) NOT NULL,
    EXPANSION VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_EXPANSION REFERENCES DESCENT.EXPANSION,
    ITEM_TYPE VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_ITEM_TYPE REFERENCES DESCENT.ITEM_TYPE,
    ATTACK_TYPE VARCHAR(30) CONSTRAINT FK_ITEM_ATTACK_TYPE REFERENCES DESCENT.ATTACK_TYPE,
    EQUIPMENT VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_EQUIPMENT REFERENCES DESCENT.EQUIPMENT,
    COST DECIMAL(3),
    RULE_CODE VARCHAR(30) NOT NULL,
    COUNT DECIMAL(1) DEFAULT 1 NOT NULL,
    CLASS VARCHAR(30) CONSTRAINT FK_ITEM_CLASS REFERENCES DESCENT.CLASS,
    IMAGE VARCHAR(30) NOT NULL);
