CREATE TABLE DESCENT.SEARCH_TRAIT (
    SEARCH VARCHAR(30) NOT NULL ,
    EXPANSION VARCHAR(30) NOT NULL,
    TRAIT VARCHAR(30) NOT NULL CONSTRAINT FK_SEARCH_TRAIT_TRAIT REFERENCES DESCENT.TRAIT,
    CONSTRAINT FK_SEARCH_TRAIT_SEARCH FOREIGN KEY (SEARCH, EXPANSION) REFERENCES DESCENT.SEARCH,
    CONSTRAINT SEARCH_TRAIT_PK PRIMARY KEY (SEARCH, EXPANSION, TRAIT));
