CREATE TABLE DESCENT.ITEM_TRAIT (
    ITEM VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_TRAIT_ITEM REFERENCES DESCENT.ITEM,
    TRAIT VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_TRAIT_TRAIT REFERENCES DESCENT.TRAIT,
    CONSTRAINT ITEM_TRAIT_PK PRIMARY KEY (ITEM, TRAIT));
