CREATE TABLE DESCENT.ITEM_DICE (
    ITEM VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_DICE_ITEM REFERENCES DESCENT.ITEM,
    DICE VARCHAR(30) NOT NULL CONSTRAINT FK_ITEM_DICE_DICE REFERENCES DESCENT.DICE,
    INDEX DECIMAL(1)  NOT NULL, 
    CONSTRAINT ITEM_DICE_PK PRIMARY KEY (ITEM, DICE, INDEX));
