CREATE TABLE DESCENT.SEARCH (
    NAME VARCHAR(30) NOT NULL,
    EXPANSION VARCHAR(30) NOT NULL CONSTRAINT FK_SEARCH_EXPANSION REFERENCES DESCENT.EXPANSION,
    MESSAGE_CODE VARCHAR(30) NOT NULL,
    ABILITY_CODE VARCHAR(30) NOT NULL,
    GOLD DECIMAL(2),
    IMAGE VARCHAR(30) NOT NULL,
    CONSTRAINT SEARCH_PK PRIMARY KEY (NAME, EXPANSION));

    DROP TABLE DESCENT.SEARCH_TRAIT;
    DROP TABLE DESCENT.SEARCH;